export const slider = document.getElementById('slider');
export const greeting = document.getElementById('greeting');
export const greetContainer = document.querySelector('.greet-container');
export const name = document.getElementById('name');
export const root = document.getElementById('root');
export const load = document.querySelector('.loading');
export const NAME_FIELD_TEXT = 'enterName';
export const IMG_HOURS = ['night', 'morning', 'afternoon', 'evening'];
export const URL = `https://api.publicapis.org/`;
